//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.4927.
// 
namespace Neopocket.News {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NewsSoap", Namespace="http://neotecnologia.net/webservice/neopocketnews")]
    public partial class News : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public News() {
            this.Url = "http://xxxcnn7767.hospedagemdesites.ws/webservice/neopocketnews/NeoPocketNewsServ" +
                "er.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://neotecnologia.net/webservice/neopocketnews/GetNews", RequestNamespace="http://neotecnologia.net/webservice/neopocketnews", ResponseNamespace="http://neotecnologia.net/webservice/neopocketnews", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetNews() {
            object[] results = this.Invoke("GetNews", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetNews(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetNews", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetNews(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://neotecnologia.net/webservice/neopocketnews/SetNews", RequestNamespace="http://neotecnologia.net/webservice/neopocketnews", ResponseNamespace="http://neotecnologia.net/webservice/neopocketnews", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetNews(string text, string codigo) {
            object[] results = this.Invoke("SetNews", new object[] {
                        text,
                        codigo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetNews(string text, string codigo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetNews", new object[] {
                        text,
                        codigo}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndSetNews(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://neotecnologia.net/webservice/neopocketnews/SetNews2", RequestNamespace="http://neotecnologia.net/webservice/neopocketnews", ResponseNamespace="http://neotecnologia.net/webservice/neopocketnews", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetNews2(string text, string codigo) {
            object[] results = this.Invoke("SetNews2", new object[] {
                        text,
                        codigo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetNews2(string text, string codigo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetNews2", new object[] {
                        text,
                        codigo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSetNews2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
